name: Ruby

on:
  push:
    branches:
      - '**'
  # pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: docker-compose build
      - name: test
        run: docker-compose run --rm rhykane bundle exec rspec
